server:
  port: 8085
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Guino-Elvis/ciclo-5/tree/main/Examen%20microservidores/back
          search-paths: config-data
          username: Guino-Elvis
          password: gino123456123
          default-label: main
  security:
    user:
      name: root
      password: s3cr3t
      # holaaasoyservidorciclo5tareaaaaa
