server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
spring:
  cloud:
    gateway:
      globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins:
              - "http://localhost:3000"
              allowedHeaders: "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
      discovery:
        locator:
          enabled: true
      routes:
        - id: alumno-service
          uri: lb://alumno-service
          predicates:
            - Path=/alumno/**
        - id: curso-service
          uri: lb://curso-service
          predicates:
            - Path=/curso/**
        - id: docente-service
          uri: lb://docente-service
          predicates:
            - Path=/docente/**
        - id: inscripccion-service
          uri: lb://inscripccion-service
          predicates:
            - Path=/inscripccion/**    

